version: '3.8'

services:
  backend:
    image: node:16
    container_name: water_service_backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/water_service_db
      - POSTGRES_URI=postgresql://postgres:password@postgres:5432/water_service_db
      - REDIS_URI=redis://redis:6379
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo
      - postgres
      - redis

  mongo:
    image: mongo:5.0
    container_name: water_service_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:15
    container_name: water_service_postgres
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: water_service_db
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:6
    container_name: water_service_redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
  postgres_data:
