version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: water_service_postgres
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: water_service_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:6
    container_name: water_service_redis
    ports:
      - "6379:6379"
      
  backend:
    image: node:18 
    container_name: water_service_backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/water_service_db
      - POSTGRES_URI=postgresql://postgres:password@postgres:5432/water_service_db
      - REDIS_URI=redis://redis:6379
    command: sh -c "npm install && npm start"
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
